cargo-features = ["edition2021"]

[package]
name = "common-functions"
version = "0.1.0"
authors = ["Datafuse Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies] # In alphabetical order
# Workspace dependencies
common-arrow = {path = "../arrow"}
common-datavalues = {path = "../datavalues"}
common-infallible = {path = "../infallible"}
common-exception = {path = "../exception"}

# Github dependencies

# Crates.io dependencies
dyn-clone = "1.0.4"
indexmap = "1.7.0"
lazy_static = "1.4.0"
bumpalo = "3.7.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bytes = "1.0.1"


[dev-dependencies]
common-datablocks = {path = "../datablocks"}
pretty_assertions = "0.7"
