cargo-features = ["edition2021"]

[package]
name = "common-profling"
version = "0.1.0"
authors = ["Datafuse Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies] # In alphabetical order
# Workspace dependencies
common-exception = {path = "../exception"}
common-runtime = {path = "../runtime"}

# Crates.io dependencies
pprof = { version = "0.5", features = ["flamegraph", "protobuf"] }
