[workspace]

members = [
    # Common
    "common/allocators",
    "common/arrow",
    "common/building",
    "common/datablocks",
    "common/datavalues",
    "common/flights",
    "common/functions",
    "common/metatypes",
    "common/infallible",
    "common/planners",
    "common/progress",
    "common/runtime",
    "common/streams",
    "common/exception",
    "common/tracing",
    "common/profiling",
    "common/kvs",
    "common/store-api",
    "common/management",

    # FuseQuery
    "fusequery/query",

    # FuseStore
    "fusestore/store",

    # Benchamrks
    "fusequery/benchmarks/nyctaxi",

    # Fuzz
    "fusequery/fuzz"
]

[profile.release]
debug = true

[profile.bench]
debug = true

[profile.dev]
split-debuginfo = "unpacked"
