cargo-features = ["edition2021"]

[package]
name = "common-management"
version = "0.1.0"
authors = ["Datafuse Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common-exception= {path = "../exception"}
common-metatypes= {path = "../metatypes"}
common-store-api= {path = "../store-api"}

async-trait = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.9.5"

[dev-dependencies]
tokio = { version = "1.8.2", features = ["macros", "rt","rt-multi-thread", "sync"] }
mockall = "0.10.2"
common-metatypes = {path = "../metatypes"}
