cargo-features = ["edition2021"]

[package]
name = "common-datavalues"
version = "0.1.0"
authors = ["Datafuse Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies] # In alphabetical order
# Workspace dependencies
common-arrow = {path = "../arrow"}
common-exception = {path = "../exception"}

# Github dependencies

# Crates.io dependencies
paste = "^1.0"
num = "^0.4"
unsafe_unwrap = "^0.1.0"
ordered-float = "2.7"
serde = { version = "1.0", features = ["derive"] }
ahash = "0.7.4"
comfy-table = "4.0.1"


[dev-dependencies]
pretty_assertions = "0.7"
