cargo-features = ["edition2021"]

[package]
name = "common-tracing"
version = "0.1.0"
authors = ["Datafuse Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies] # In alphabetical order
tracing = "0.1.26"
tracing-appender = "0.1.2"
tracing-bunyan-formatter = "0.2"
tracing-futures = { version = "0.2.5", default-features = false }
tracing-subscriber = "0.2.19"
