cargo-features = ["edition2021"]

[package]
name = "common-runtime"
version = "0.1.0"
authors = ["Datafuse Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies] # In alphabetical order
# Workspace dependencies
common-exception = {path = "../exception"}

# Github dependencies

# Crates.io dependencies
tokio = { version = "1.8.2", features = ["macros", "rt","rt-multi-thread", "sync"] }

[dev-dependencies]

